# Generated by Django 4.0.6 on 2022-08-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
